# Generated by Django 5.2.1 on 2025-05-31 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rezerv',
            name='date',
        ),
        migrations.RemoveField(
            model_name='rezerv',
            name='email',
        ),
        migrations.RemoveField(
            model_name='rezerv',
            name='time',
        ),
        migrations.AddField(
            model_name='rezerv',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='rezerv',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rezerv',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
