# Generated by Django 5.2.1 on 2025-05-31 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0007_alter_rezerv_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='rezerv',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
