# Generated by Django 5.2.1 on 2025-05-31 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0008_rezerv_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_lastname', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_sms', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
