# Generated by Django 5.2.1 on 2025-05-31 20:47


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0009_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='carousel_images/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='carousel_images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='carousel_images/')),
            ],
        ),
    ]
