# Generated by Django 5.2.1 on 2025-05-31 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0010_carouselimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='rezerv',
            name='is_arrival',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
