# Generated by Django 5.1.5 on 2025-05-31 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0011_rezerv_is_arrival'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contact_phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
