# Generated by Django 5.2.1 on 2025-06-26 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0014_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rezerv',
            name='image',
        ),
        migrations.RemoveField(
            model_name='rezerv',
            name='phone',
        ),
        migrations.AddField(
            model_name='rezerv',
            name='big_suitcases',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rezerv',
            name='cancel_before_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rezerv',
            name='cross_border_allowed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='rezerv',
            name='cross_border_assistance',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='rezerv',
            name='cross_border_assistance_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='rezerv',
            name='cross_border_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='rezerv',
            name='cross_border_km_limit',
            field=models.IntegerField(blank=True, default=1000, null=True),
        ),
        migrations.AddField(
            model_name='rezerv',
            name='delivery_outside_hours',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='rezerv',
            name='deposit_required',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='rezerv',
            name='engine_capacity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rezerv',
            name='fuel_policy',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rezerv',
            name='fuel_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rezerv',
            name='guarantee_high_season',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='rezerv',
            name='guarantee_low_season',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='rezerv',
            name='min_days_high',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rezerv',
            name='min_days_low',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rezerv',
            name='notice_period',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rezerv',
            name='seats',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rezerv',
            name='small_suitcases',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rezerv',
            name='transmission',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rezerv',
            name='working_hours',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rezerv',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rezerv',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='CarOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price_per_day', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='aplication.rezerv')),
            ],
        ),
        migrations.CreateModel(
            name='CarPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='car_photos/')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='aplication.rezerv')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_locations', to='aplication.rezerv')),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=6)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_options', to='aplication.rezerv')),
            ],
        ),
    ]
