# Generated by Django 5.2.1 on 2025-06-26 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0015_remove_rezerv_image_remove_rezerv_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rezerv',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='rezervpage/'),
        ),
    ]
