# Generated by Django 5.2.1 on 2025-06-26 20:36

import aplication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0016_rezerv_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carphoto',
            name='image',
            field=models.ImageField(blank=True, default=aplication.models.default_image, null=True, upload_to='car_photos/'),
        ),
    ]
