# Generated by Django 5.2.1 on 2025-06-26 20:38

import aplication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0017_alter_carphoto_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezerv',
            name='image',
            field=models.ImageField(blank=True, default=aplication.models.default_image, null=True, upload_to='rezervpage/'),
        ),
    ]
