# Generated by Django 5.2.1 on 2025-06-26 20:38



from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0017_alter_carphoto_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezerv',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='rezervpage/'),
        ),
    ]


