# Generated by Django 5.1.5 on 2025-06-28 17:49


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0018_alter_rezerv_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carphoto',
            name='image',
            field=models.ImageField( upload_to='car_photos/'),
        ),
    ]
