# Generated by Django 5.1.5 on 2025-06-30 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0019_alter_carphoto_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='rezerv',
            name='is_audi',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='rezerv',
            name='is_bmvp',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='rezerv',
            name='is_compact',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='rezerv',
            name='is_economy',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='rezerv',
            name='is_luxury',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='rezerv',
            name='is_mercedes',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='rezerv',
            name='is_suv',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
