# Generated by Django 5.1.5 on 2025-07-01 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0020_rezerv_is_audi_rezerv_is_bmvp_rezerv_is_compact_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rezerv',
            old_name='is_bmvp',
            new_name='is_bmv',
        ),
    ]
