# Generated by Django 5.1.5 on 2025-07-01 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0021_rename_is_bmvp_rezerv_is_bmv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rezerv',
            name='is_compact',
        ),
    ]
