# Generated by Django 5.1.5 on 2025-07-01 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0022_remove_rezerv_is_compact'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='dropoff_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='pickup_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
