# Generated by Django 5.1.5 on 2025-07-01 19:04

import hykarent.aplication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0023_reservation_dropoff_location_reservation_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselimage',
            name='image',
            field=models.ImageField(blank=True, default=hykarent.aplication.models.default_image, null=True, upload_to='carousel_images/'),
        ),
        migrations.AlterField(
            model_name='carouselimage',
            name='image1',
            field=models.ImageField(blank=True, default=hykarent.aplication.models.default_image, null=True, upload_to='carousel_images/'),
        ),
        migrations.AlterField(
            model_name='carouselimage',
            name='image3',
            field=models.ImageField(blank=True, default=hykarent.aplication.models.default_image, null=True, upload_to='carousel_images/'),
        ),
        migrations.AlterField(
            model_name='carphoto',
            name='image',
            field=models.ImageField(default=hykarent.aplication.models.default_image, upload_to='car_photos/'),
        ),
        migrations.AlterField(
            model_name='rezerv',
            name='image',
            field=models.ImageField(blank=True, default=hykarent.aplication.models.default_image, null=True, upload_to='rezervpage/'),
        ),
    ]
