# Generated by Django 5.1.5 on 2025-07-02 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0024_alter_carouselimage_image_alter_carouselimage_image1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryLocation',
        ),
    ]
