# Generated by Django 5.1.5 on 2025-07-02 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0025_delete_deliverylocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='rezerv',
            name='dropoff_location',
            field=models.CharField(blank=True, choices=[('fier', 'Fier'), ('tirane', 'Tirane'), ('gjirokaster', 'Gjirokaster'), ('vlore', 'Vlore')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='rezerv',
            name='pickup_location',
            field=models.CharField(blank=True, choices=[('fier', 'Fier'), ('tirane', 'Tirane'), ('gjirokaster', 'Gjirokaster'), ('vlore', 'Vlore')], max_length=20, null=True),
        ),
    ]
