# Generated by Django 5.1.5 on 2025-07-02 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0026_rezerv_dropoff_location_rezerv_pickup_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rezerv',
            name='dropoff_location',
        ),
        migrations.RemoveField(
            model_name='rezerv',
            name='pickup_location',
        ),
    ]
