# Generated by Django 5.1.5 on 2025-08-25 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0027_remove_rezerv_dropoff_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rezerv',
            name='is_audi',
        ),
        migrations.RemoveField(
            model_name='rezerv',
            name='is_bmv',
        ),
        migrations.RemoveField(
            model_name='rezerv',
            name='is_mercedes',
        ),
    ]
